
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Data;
using System.Reflection;
using popingui.Models;

namespace popingui {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        private Terminal.Gui.TableView t1 = new();

        private void InitializeComponent() {
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";

            int width = 0;
            foreach (DataColumn column in Program.Dt.Columns)
            {
                width = width + column.Caption.Length + 1;
            }

            t1 = new TableView () {
                X = 0,
                Y = 0,
                Width = 160,
                Height = Program.config.Hosts.Count()+3
            };

            t1.Table = Program.Dt;

            this.Add(t1);
        }
    }
}
